// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OnError is an autogenerated mock type for the OnError type
type OnError struct {
	mock.Mock
}

// Execute provides a mock function with given fields: err
func (_m *OnError) Execute(err error) {
	_m.Called(err)
}

type mockConstructorTestingTNewOnError interface {
	mock.TestingT
	Cleanup(func())
}

// NewOnError creates a new instance of OnError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOnError(t mockConstructorTestingTNewOnError) *OnError {
	mock := &OnError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
