recursive: true
all: true
dir: "pkg/mocks/{{.PackageName}}mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}mocks"
with-expecter: true
packages:
  github.com/hostfactor/diazo/pkg/userfiles:
    config: { }
  github.com/hostfactor/diazo/pkg/actions:
    config: { }
