// Code generated by mockery v2.9.4. DO NOT EDIT.

package diazo

import (
	providerconfig "github.com/hostfactor/api/go/providerconfig"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// SyncVersions provides a mock function with given fields: syncer, spec
func (_m *MockClient) SyncVersions(syncer VersionSyncer, spec *providerconfig.VersionSyncSpec) error {
	ret := _m.Called(syncer, spec)

	var r0 error
	if rf, ok := ret.Get(0).(func(VersionSyncer, *providerconfig.VersionSyncSpec) error); ok {
		r0 = rf(syncer, spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
