// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// BlobCreator is an autogenerated mock type for the BlobCreator type
type BlobCreator struct {
	mock.Mock
}

// CreateBlob provides a mock function with given fields: fp
func (_m *BlobCreator) CreateBlob(fp string) (io.WriteCloser, error) {
	ret := _m.Called(fp)

	var r0 io.WriteCloser
	if rf, ok := ret.Get(0).(func(string) io.WriteCloser); ok {
		r0 = rf(fp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBlobCreator interface {
	mock.TestingT
	Cleanup(func())
}

// NewBlobCreator creates a new instance of BlobCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBlobCreator(t mockConstructorTestingTNewBlobCreator) *BlobCreator {
	mock := &BlobCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
