// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// KeyResolver is an autogenerated mock type for the KeyResolver type
type KeyResolver struct {
	mock.Mock
}

// Execute provides a mock function with given fields: key
func (_m *KeyResolver) Execute(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewKeyResolver interface {
	mock.TestingT
	Cleanup(func())
}

// NewKeyResolver creates a new instance of KeyResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKeyResolver(t mockConstructorTestingTNewKeyResolver) *KeyResolver {
	mock := &KeyResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
