// Code generated by mockery v2.9.4. DO NOT EDIT.

package containers

import mock "github.com/stretchr/testify/mock"

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

// CopyImage provides a mock function with given fields: src, dst
func (_m *MockClient) CopyImage(src ImageURL, dst ImageURL) error {
	ret := _m.Called(src, dst)

	var r0 error
	if rf, ok := ret.Get(0).(func(ImageURL, ImageURL) error); ok {
		r0 = rf(src, dst)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRepositoryTags provides a mock function with given fields: i
func (_m *MockClient) GetRepositoryTags(i ImageURL) ([]string, error) {
	ret := _m.Called(i)

	var r0 []string
	if rf, ok := ret.Get(0).(func(ImageURL) []string); ok {
		r0 = rf(i)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(ImageURL) error); ok {
		r1 = rf(i)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: username, password, registry
func (_m *MockClient) Login(username string, password string, registry string) error {
	ret := _m.Called(username, password, registry)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(username, password, registry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
