// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EntryStore is an autogenerated mock type for the EntryStore type
type EntryStore struct {
	mock.Mock
}

// GetStringValue provides a mock function with given fields: key
func (_m *EntryStore) GetStringValue(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewEntryStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewEntryStore creates a new instance of EntryStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEntryStore(t mockConstructorTestingTNewEntryStore) *EntryStore {
	mock := &EntryStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
