// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ErrorIser is an autogenerated mock type for the ErrorIser type
type ErrorIser struct {
	mock.Mock
}

// Is provides a mock function with given fields: err
func (_m *ErrorIser) Is(err error) bool {
	ret := _m.Called(err)

	var r0 bool
	if rf, ok := ret.Get(0).(func(error) bool); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewErrorIser interface {
	mock.TestingT
	Cleanup(func())
}

// NewErrorIser creates a new instance of ErrorIser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewErrorIser(t mockConstructorTestingTNewErrorIser) *ErrorIser {
	mock := &ErrorIser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
