// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ImageURLGetter is an autogenerated mock type for the ImageURLGetter type
type ImageURLGetter struct {
	mock.Mock
}

// Path provides a mock function with given fields:
func (_m *ImageURLGetter) Path() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// String provides a mock function with given fields:
func (_m *ImageURLGetter) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewImageURLGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewImageURLGetter creates a new instance of ImageURLGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewImageURLGetter(t mockConstructorTestingTNewImageURLGetter) *ImageURLGetter {
	mock := &ImageURLGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
