// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// OnErrorFunc is an autogenerated mock type for the OnErrorFunc type
type OnErrorFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: err, req
func (_m *OnErrorFunc) Execute(err error, req *http.Request) {
	_m.Called(err, req)
}

type mockConstructorTestingTNewOnErrorFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewOnErrorFunc creates a new instance of OnErrorFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOnErrorFunc(t mockConstructorTestingTNewOnErrorFunc) *OnErrorFunc {
	mock := &OnErrorFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
