// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OnError is an autogenerated mock type for the OnError type
type OnError struct {
	mock.Mock
}

// Execute provides a mock function with given fields: err
func (_m *OnError) Execute(err error) {
	_m.Called(err)
}
