// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	remoteversion "github.com/hostfactor/diazo/pkg/version/remoteversion"
	mock "github.com/stretchr/testify/mock"
)

// VersionSyncer is an autogenerated mock type for the VersionSyncer type
type VersionSyncer struct {
	mock.Mock
}

// SyncVersions provides a mock function with given fields: rv
func (_m *VersionSyncer) SyncVersions(rv *remoteversion.RemoteVersion) error {
	ret := _m.Called(rv)

	var r0 error
	if rf, ok := ret.Get(0).(func(*remoteversion.RemoteVersion) error); ok {
		r0 = rf(rv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
