// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	reaction "github.com/hostfactor/diazo/pkg/reaction"
	mock "github.com/stretchr/testify/mock"
)

// WatchLogFunc is an autogenerated mock type for the WatchLogFunc type
type WatchLogFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ll
func (_m *WatchLogFunc) Execute(ll reaction.LogLine) {
	_m.Called(ll)
}

type mockConstructorTestingTNewWatchLogFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewWatchLogFunc creates a new instance of WatchLogFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWatchLogFunc(t mockConstructorTestingTNewWatchLogFunc) *WatchLogFunc {
	mock := &WatchLogFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
