// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	containers "github.com/hostfactor/diazo/pkg/containers"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CopyImage provides a mock function with given fields: src, dst
func (_m *Client) CopyImage(src containers.ImageURL, dst containers.ImageURL) error {
	ret := _m.Called(src, dst)

	var r0 error
	if rf, ok := ret.Get(0).(func(containers.ImageURL, containers.ImageURL) error); ok {
		r0 = rf(src, dst)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRepositoryTags provides a mock function with given fields: i, opts
func (_m *Client) GetRepositoryTags(i containers.ImageURL, opts containers.GetRepositoryTagsOpts) ([]string, error) {
	ret := _m.Called(i, opts)

	var r0 []string
	if rf, ok := ret.Get(0).(func(containers.ImageURL, containers.GetRepositoryTagsOpts) []string); ok {
		r0 = rf(i, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(containers.ImageURL, containers.GetRepositoryTagsOpts) error); ok {
		r1 = rf(i, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: username, password, registry
func (_m *Client) Login(username string, password string, registry string) error {
	ret := _m.Called(username, password, registry)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(username, password, registry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
