// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	providerconfig "github.com/hostfactor/api/go/providerconfig"
	mock "github.com/stretchr/testify/mock"

	remoteversion "github.com/hostfactor/diazo/pkg/version/remoteversion"
)

// VersionFetcher is an autogenerated mock type for the VersionFetcher type
type VersionFetcher struct {
	mock.Mock
}

// FetchVersions provides a mock function with given fields: cr
func (_m *VersionFetcher) FetchVersions(cr *providerconfig.RemoteVersionSource) ([]*remoteversion.RemoteVersion, error) {
	ret := _m.Called(cr)

	var r0 []*remoteversion.RemoteVersion
	if rf, ok := ret.Get(0).(func(*providerconfig.RemoteVersionSource) []*remoteversion.RemoteVersion); ok {
		r0 = rf(cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*remoteversion.RemoteVersion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*providerconfig.RemoteVersionSource) error); ok {
		r1 = rf(cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
