// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	actions "github.com/hostfactor/api/go/blueprint/actions"
	mock "github.com/stretchr/testify/mock"

	provideractions "github.com/hostfactor/diazo/pkg/provideractions"

	reaction "github.com/hostfactor/api/go/blueprint/reaction"
)

// FileReactionActionBuilder is an autogenerated mock type for the FileReactionActionBuilder type
type FileReactionActionBuilder struct {
	mock.Mock
}

// Build provides a mock function with given fields:
func (_m *FileReactionActionBuilder) Build() *reaction.FileReactionAction {
	ret := _m.Called()

	var r0 *reaction.FileReactionAction
	if rf, ok := ret.Get(0).(func() *reaction.FileReactionAction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reaction.FileReactionAction)
		}
	}

	return r0
}

// Upload provides a mock function with given fields: from, filename, folder
func (_m *FileReactionActionBuilder) Upload(from string, filename string, folder string) provideractions.FileReactionActionBuilder {
	ret := _m.Called(from, filename, folder)

	var r0 provideractions.FileReactionActionBuilder
	if rf, ok := ret.Get(0).(func(string, string, string) provideractions.FileReactionActionBuilder); ok {
		r0 = rf(from, filename, folder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provideractions.FileReactionActionBuilder)
		}
	}

	return r0
}

// ZipFolder provides a mock function with given fields: to, entries
func (_m *FileReactionActionBuilder) ZipFolder(to string, entries ...*actions.ZipFileEntry) provideractions.FileReactionActionBuilder {
	_va := make([]interface{}, len(entries))
	for _i := range entries {
		_va[_i] = entries[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, to)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 provideractions.FileReactionActionBuilder
	if rf, ok := ret.Get(0).(func(string, ...*actions.ZipFileEntry) provideractions.FileReactionActionBuilder); ok {
		r0 = rf(to, entries...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provideractions.FileReactionActionBuilder)
		}
	}

	return r0
}

type mockConstructorTestingTNewFileReactionActionBuilder interface {
	mock.TestingT
	Cleanup(func())
}

// NewFileReactionActionBuilder creates a new instance of FileReactionActionBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFileReactionActionBuilder(t mockConstructorTestingTNewFileReactionActionBuilder) *FileReactionActionBuilder {
	mock := &FileReactionActionBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
