// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StringValueGetter is an autogenerated mock type for the StringValueGetter type
type StringValueGetter struct {
	mock.Mock
}

// GetStringValue provides a mock function with given fields: key
func (_m *StringValueGetter) GetStringValue(key string) string {
	ret := _m.Called(key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewStringValueGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewStringValueGetter creates a new instance of StringValueGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStringValueGetter(t mockConstructorTestingTNewStringValueGetter) *StringValueGetter {
	mock := &StringValueGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
