// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	remoteversion "github.com/hostfactor/diazo/pkg/version/remoteversion"
	mock "github.com/stretchr/testify/mock"
)

// Transformer is an autogenerated mock type for the Transformer type
type Transformer struct {
	mock.Mock
}

// TransformRemoteVersion provides a mock function with given fields: ver
func (_m *Transformer) TransformRemoteVersion(ver *remoteversion.RemoteVersion) *remoteversion.RemoteVersion {
	ret := _m.Called(ver)

	var r0 *remoteversion.RemoteVersion
	if rf, ok := ret.Get(0).(func(*remoteversion.RemoteVersion) *remoteversion.RemoteVersion); ok {
		r0 = rf(ver)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*remoteversion.RemoteVersion)
		}
	}

	return r0
}
