// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	fsnotify "github.com/fsnotify/fsnotify"
	mock "github.com/stretchr/testify/mock"
)

// WatchFunc is an autogenerated mock type for the WatchFunc type
type WatchFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: event
func (_m *WatchFunc) Execute(event fsnotify.Event) {
	_m.Called(event)
}
