// Code generated by mockery v2.36.0. DO NOT EDIT.

package userfilesmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

type Server_Expecter struct {
	mock *mock.Mock
}

func (_m *Server) EXPECT() *Server_Expecter {
	return &Server_Expecter{mock: &_m.Mock}
}

// ListenAndServe provides a mock function with given fields:
func (_m *Server) ListenAndServe() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Server_ListenAndServe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenAndServe'
type Server_ListenAndServe_Call struct {
	*mock.Call
}

// ListenAndServe is a helper method to define mock.On call
func (_e *Server_Expecter) ListenAndServe() *Server_ListenAndServe_Call {
	return &Server_ListenAndServe_Call{Call: _e.mock.On("ListenAndServe")}
}

func (_c *Server_ListenAndServe_Call) Run(run func()) *Server_ListenAndServe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Server_ListenAndServe_Call) Return(_a0 error) *Server_ListenAndServe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Server_ListenAndServe_Call) RunAndReturn(run func() error) *Server_ListenAndServe_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *Server) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Server_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type Server_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Server_Expecter) Shutdown(ctx interface{}) *Server_Shutdown_Call {
	return &Server_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *Server_Shutdown_Call) Run(run func(ctx context.Context)) *Server_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Server_Shutdown_Call) Return(_a0 error) *Server_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Server_Shutdown_Call) RunAndReturn(run func(context.Context) error) *Server_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// NewServer creates a new instance of Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Server {
	mock := &Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
