// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	fileactions "github.com/hostfactor/diazo/pkg/actions/fileactions"
	mock "github.com/stretchr/testify/mock"
)

// OnDownloadFunc is an autogenerated mock type for the OnDownloadFunc type
type OnDownloadFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: params
func (_m *OnDownloadFunc) Execute(params fileactions.OnDownloadFuncParams) {
	_m.Called(params)
}

type mockConstructorTestingTNewOnDownloadFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewOnDownloadFunc creates a new instance of OnDownloadFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOnDownloadFunc(t mockConstructorTestingTNewOnDownloadFunc) *OnDownloadFunc {
	mock := &OnDownloadFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
