// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	fileactions "github.com/hostfactor/diazo/pkg/fileactions"
	mock "github.com/stretchr/testify/mock"
)

// OnDownloadFunc is an autogenerated mock type for the OnDownloadFunc type
type OnDownloadFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: params
func (_m *OnDownloadFunc) Execute(params fileactions.OnDownloadFuncParams) {
	_m.Called(params)
}
